ogsr_engine/xrGame/Weapon.cpp
ogsr_engine/xrGame/WeaponMagazined.cpp

Make sure to always init m_fRTZoomFactor, m_bScopeDynamicZoom and m_fScopeZoomFactor on InitAddons.
Иначе получалось, что если прицел ставить позже чем спаун - m_fRTZoomFactor был не инициализированный и при прицеливании получалось вот так вот  https://www.youtube.com/watch?v=dFuSXyL6OcU&feature=youtu.be
Так же, поскольку у Weapon есть из наследников только Нож и WeaponMagazined, но перенес все инициализации зума в InitAddons(), который вызывается всегда - при спауне, при загрузке и при аттаче\деаттаче аддонов.

Fixed issue with dynamic zoom for attachable scopes.

---

ogsr_engine/build_config_defines.h
ogsr_engine/xrGame/Level_Bullet_Manager.cpp
ogsr_engine/xrGame/Weapon.cpp
ogsr_engine/xrGame/Weapon.h
ogsr_engine/xrGame/WeaponAmmo.cpp
ogsr_engine/xrGame/WeaponAmmo.h

1. В цену орудия будет учитываться цена аддонов на нем.
2. Анимация anim_idle_moving будет проигрываться и для состояний actor->is_actor_walking() || actor->is_actor_creeping() || actor->is_actor_crouching(). Под дефайном MORE_WPN_IDLE_MOVING_STATES
3. Добавлен параметр k_bullet_speed для секции амуниции. Позволяем менять скорость полета пули для определенного типа амуниции. По умолчанию 1 - потому не прятал.

Доработки по оружейке

---

ogsr_engine/xrGame/WeaponMagazined.cpp

Исправления к прошлому коммиту.
Для случая когда оружие без прицела - нужно читать параметры из секции самого оружия.

Fixed a typo: *m_sScopeName > cNameSect() in InitAddons() method

---

ogsr_engine/xrGame/ui/UIDragDropListEx.cpp
ogsr_engine/xrGame/ui/UIScrollBar.cpp

1. (простая часть) теперь если во время прокрутки мышкой в dragdroplistex зажать Shift - будет крутить в 3 раза быстрее.
2. (сложная часть) долго я искал, почему при определенных условиях прокрутка инвентаря "недокручивает" последний ряд даже при нормальном конфиге инвентаря. дело в том, что в UIDragDropListEx при инициализации сколлбара спутаны понятия высоты в пикселях и высоты в ячейках (строках). Нельзя указывать Range и StepSize в пикселях, а PageSize в строках. Потому как потом одно и другого будет вычитаться и получается полный бред. Поставил SetPageSize(1) и все стало работать нормально. А раньше правильно оно могло работать только тогда, если значения PageSize и StepSize совпадали численно.

Исправление кривого скролла в dragdroplistex

---

ogsr_engine/xrGame/ui/UIDragDropListEx.cpp
ogsr_engine/xrGame/ui/UIScrollBar.cpp
ogsr_engine/xrGame/ui/UIScrollBar.h
ogsr_engine/xrGame/ui/uiinventorywnd2.cpp

* Fix ScrollBar Refresh logic to not move content due to rounding error
* Fix issue when CUIDragDropListEx show wrong content due after auto grow in the middle of scroll
* Added logic to save main inventory position on updates

A few more fixes to scroll managment in CUIDragDropListEx:

---

ogsr_engine/xrGame/derived_client_classes.cpp
ogsr_engine/xrGame/map_location.cpp

- Export scope_inertion_factor into scripts
- Fixed spots positions on minimap
Не знаю чем руководствовались люди когда при расчете положения точек на миникарте брали уловие (map->Heading()) ? false : true. В таком случае никогда не выполнялась коррекция для широкоформатиников и точки плавали по овалу.

Правки по миникарте

---

ogsr_engine/xrGame/base_client_classes.h
ogsr_engine/xrGame/base_client_classes_script.cpp
ogsr_engine/xr_3da/ParticleCustom.h
ogsr_engine/xr_3da/ResourceManager.cpp
ogsr_engine/xr_3da/ResourceManager.h
ogsr_engine/xr_3da/ResourceManager_Resources.cpp

Added methods to enumerate children of IRender_Visual
Added support of texture replacement in memory
Пример скрипта для использования:
```lua
local obj = db.actor:active_item()
local vis = obj:get_hud_visual()
if vis then
log1("*********** child:")
for i = 0, 15 do
local c = vis:child(i) 
if c then
for ti = 0, 15 do    
local tr = c:get_texture(ti)
if tr then
local tname = tr:get_name()
log1("child=" .. i .. " tex_id=" .. ti .. " name=" .. tname .. " ref_count=" .. tr.ref_count)
end
end
end
end
end
```
```lua
log1("texture_find test for name: act\\act_arm_perchatka_cs")
local t1 = texture_find("act\\act_arm_perchatka_cs") -- возвращает таблицу: ключ имя текстуры, значение объект
if t1 then
t1 = t1[ "act\\act_arm_perchatka_cs" ]
log1("found, name=" .. t1:get_name())
local ntname = …
```

Работа с текстурами (поиск, замена)

---

ogsr_engine/COMMON_AI/xrServer_Objects_ALife_Items.cpp
ogsr_engine/COMMON_AI/xrServer_Objects_ALife_Items_script2.cpp
ogsr_engine/COMMON_AI/xrServer_Objects_ALife_Items_script3.cpp
ogsr_engine/COMMON_AI/xrServer_Objects_ALife_script.cpp
ogsr_engine/xrGame/derived_client_classes.cpp
ogsr_engine/xrGame/ui/UIScrollBar.cpp
ogsr_engine/xr_3da/device.cpp

Цель - дать возможность указать все основные параметры оружия через серверный объект при спауне. При спауне используется только методы STATE_Read\Write. Потому перенес туда новые свойства, все по аналогии с тем что уже было.
Added method get_weapon_m()/get_weapon_gl to access Weapon objects.
Added STATE_Read/STATE_Write for new properties to allow to override it during spawn.
Extend of CSE_ALifeItemWeaponMagazined:
* current_fire_mode
Extend of CSE_ALifeItemWeaponMagazinedWGL:
* ammo_type_2
* ammo_elapsed_2

Расширение серверный объектов.

---

ogsr_engine/xrGame/base_client_classes_script.cpp
ogsr_engine/xr_3da/ResourceManager.h
ogsr_engine/xr_3da/ResourceManager_Resources.cpp
ogsr_engine/xr_3da/SH_Texture.cpp
ogsr_engine/xr_3da/SH_Texture.h

Эксперименты показали, что менять имя текстуры плохая затея - при следующей загрузке сохранения начинаются странные ключи с **CResourceManager**, создаются копии текстур с разными именами (оригинальное и то что задали при подмене).
Переделал по другому, раз это костыль состояния, то будем просто вгружать новую текстуру без подмены имени. Так стало работать нормально, все работает после save\load и при выходе из игры не ругается. Да и скрипты для работы стали проще.
Было:
```
t:unload()
t:set_name(name)
t:load()
```
Стало:
```
t:load(name)
```

A different way of texture replacement

---

ogsr_engine/COMMON_AI/xrServer_Objects_ALife_Items.cpp

Поспешил я убирать проверку позиции в пакете в STATE_Read
Это будет ломать спаун из all.spawn при НИ и бить сохранения.
Но, возможно тут лучше проверять через проверку m_wVersion и увеличить
https://github.com/KRodinn/OGSR-Engine/blob/328c0c142852f1409d47c1de8c42b78494628bf4/ogsr_engine/COMMON_AI/xrServer_Objects.h#L154

Проверка пакета при чтении новых полей в STATE_Read

---

ogsr_engine/xrGame/WeaponRPG7.cpp
ogsr_engine/xrGame/WeaponRPG7.h
ogsr_engine/xrGame/ui/UICarBodyWnd.cpp
ogsr_engine/xrGame/ui/UICarBodyWnd.h
ogsr_engine/xrGame/ui/UITradeWnd.cpp
ogsr_engine/xrGame/ui/UITradeWnd.h
ogsr_engine/xrGame/weaponBM16.cpp
ogsr_engine/xrGame/weaponBM16.h

* Исправлен баг с появление на доли секунды заряда при перезарядке у РПГ7 (из xrOxygen)
* Привел в порядок код в trade/car_body wnd для перемещения пачек предметов. И добавил перенос пачек перетягиванием при зажатом Shift
* Уточнения по анимации для класса BM16:
1. Для улучшения совместимости с ванильными конфигами, при отсутствии **anim_idle_sprint_1-2/anim_idle_moving_1-2** будут браться **anim_idle_1-2** соответственно, они были обязательные для этого класса с самого начала. Но все равно в чистом ТЧ нету анимации спринта с закрытыми курками - будет постоянно открывать их при спринте.
2. Добавил анимации **anim_shoot_2, anim_draw_1-2, anim_holster_1-2** из ЗП. Теперь почти все анимации ЗП поддерживаются.
3. Вместо **anim_zoomedidle_2** можно писать нормальный **anim_zoomed_idle_2**. Да …

Мелкий правки 2

---

ogsr_engine/xrGame/script_actor.cpp
ogsr_engine/xrGame/ui/UICustomEdit.cpp
ogsr_engine/xrGame/ui/UICustomEdit.h
ogsr_engine/xrGame/ui/UIMapWnd.cpp
ogsr_engine/xrGame/ui/UIMapWndActions.cpp
ogsr_engine/xrGame/ui/UIPdaSpot.cpp
ogsr_engine/xrGame/ui/UIPdaWnd.cpp
ogsr_engine/xrGame/ui/UIPdaWnd.h

Work on UICustomEdit:
* Fixed issues with focus capture (for PDA mainly)
* Smaller wait time for auto repeat of character when hold button
* Now auto repeat will work in edit box when game on pause
Work on PDA:
* Auto focus pda spot name control evert time on open
* Increate speed of animation when use map in PDA
Extract m_fV_SatietyPower into scirpt with name satiety_power_v

Работа по UI

---

ogsr_engine/xrGame/ui/UIItemInfo.cpp
ogsr_engine/xrGame/ui/UIItemInfo.h

Добавил возможность показывать любые дополнительные свойства выбранного предмета в инвентарях. Работает через вызов движком lua функтора в который передается выбраны предмет и UIStatic на который можно добавить все что нужно для отображения.
Для включение нужно добавить в system.ltx
```
[engine_callbacks]
ui_item_info_callback=ui_custom_params.try_add_custom
```
**ui_custom_params.try_add_custom** - скриптовый метод с сигнатурой:
**try_add_custom(obj, wnd)**
Перед вызовом статик wnd всегда очищается движком.
Если метод вернул true - статик будет показан в свойствах предмета, false - нет.
Пример реализации скрипта для отображения свойств eatable_item для ТЧ  https://gist.github.com/joye-ramone/a9c9b6dfc43202b46bc41bde08b0082d

Возможность показывать любые дополнительные свойства выбранного предмета

---

ogsr_engine/xrGame/ScriptXMLInit.cpp
ogsr_engine/xrGame/ScriptXMLInit.h
ogsr_engine/xrGame/ui/UIInventoryWnd.cpp
ogsr_engine/xrGame/ui/UIInventoryWnd.h
ogsr_engine/xrGame/ui/UIItemInfo.cpp
ogsr_engine/xrGame/ui/UIItemInfo.h
ogsr_engine/xrGame/ui/UIOutfitInfo.cpp
ogsr_engine/xrGame/ui/UIOutfitInfo.h
ogsr_engine/xrGame/ui/UIWindow_script.cpp

1. Теперь в **ui_item_info_callback** приходит весь инвентарный UIDesc (xml descr_list). Скрипт решает, что с ним делать и что добавлять. Обновил gist at https://gist.github.com/joye-ramone/a9c9b6dfc43202b46bc41bde08b0082d
2. Добавил новый **ui_actor_info_callback** - вызывается при обновлении outfit_info в инвентаре ГГ. Сигнатура: **try_add_actor_custom(list, obj)**, где list - CUIScrollView (xml outfit_info:scroll_view in inventory_new.xml). obj - текущий костюм ГГ, если нету - nil.
3. Убрал постоянную перерисовку outfit_info в инвентаре ГГ. outfit_info показывает только параметры костюма + артефакты с пояса. Зачем ее обновлять каждый апдейт не ясно. Теперь будет если, любой предмет сделал Item2Slot\Item2Belt\Item2Ruck\Item_Drop.
4. Добавил DetachAll method to CUIWindow export

Доработки для UI callbacks

---

ogsr_engine/xrGame/WeaponPistol.cpp

Для пистолетов есть поддержка анимаций оружия в одной руке когда ГГ в машине или другом холдере.
Добавил инициализацию туда анимаций anim_idle_sprint_empty\anim_idle_moving_empty иначе если набегу запрыгивать в машину с пустим пистолетом - вылет был.

Поправил анимации для пистолета anim_idle_sprint_empty\anim_idle_moving_empty

---

ogsr_engine/xrGame/Weapon.cpp
ogsr_engine/xrGame/ai/monsters/controller/controller_psy_hit.cpp
ogsr_engine/xrGame/ai/monsters/controller/controller_psy_hit.h
ogsr_engine/xrGame/ui/UICarBodyWnd.cpp
ogsr_engine/xrGame/ui/UICellCustomItems.cpp
ogsr_engine/xrGame/ui/UIInventoryWnd.cpp
ogsr_engine/xrGame/ui/UIMainIngameWnd.cpp
ogsr_engine/xrGame/ui/UITradeWnd.cpp
ogsr_engine/xr_3da/ResourceManager_Loader.cpp

1. Added 2 new parameters to controller config section:
* **tube_disable_camera_effect** - allow to disable actor camera fly during tube attack
* **tube_disable_actor_block** - allow to disable actor control block during tube attack
Both optional and off by default
2. Fixed issue with hide of item properties menu in car body wnd
3. Fixed issue with permanent PickUpItem icon if load game with it visible (from oxygen)
4. Added more details to "Version conflict in shader ... " message

Новые параметры для контрика + правки багов

---

ogsr_engine/xrGame/ActorCondition.cpp
ogsr_engine/xrGame/Artifact.cpp
ogsr_engine/xrGame/Artifact.h
ogsr_engine/xrGame/Bolt.cpp
ogsr_engine/xrGame/Bolt.h
ogsr_engine/xrGame/Weapon.cpp
ogsr_engine/xrGame/Weapon.h
ogsr_engine/xrGame/WeaponMagazined.cpp
ogsr_engine/xrGame/WeaponMagazined.h
ogsr_engine/xrGame/WeaponMagazinedWGrenade.cpp
ogsr_engine/xrGame/WeaponMagazinedWGrenade.h
ogsr_engine/xrGame/WeaponShotgun.cpp
ogsr_engine/xrGame/ui/UICarBodyWnd.cpp
ogsr_engine/xrGame/ui/UIInventoryWnd3.cpp

1. Weapons dynamic zoom changes:
* Added zoom change sound via **snd_zoom_change** in weapon section
* Weapon will use minimal possible zoom level in ogse zoom mode by default.
* Dynamic Zoom steps count set to 4
2. Added check for IsScopeAttached in UpdateSecondVP to fix lags even for weapons without scope
3. Added logic to apply same rules to max_weight calculation for jump and walk power loss
4. Weapons with GL:
* Switch to GL mode when unload magazine only if GL is present
* Update addons flags only after switch GL and unload magazine when detaching GL.
* Fixed spawn of CWeaponMagazinedWGrenade in GL mode - it will update zoom offset and call lua callback
5. HUD:
* Added icon for bolt when it active item
* Added icon and text info for artefact when it active item
Minor changes:
* …

Мелкие правки и доработки

---

ogsr_engine/COMMON_AI/xrServer_Objects_ALife_Items.h
ogsr_engine/xrGame/Actor_Flags.h
ogsr_engine/xrGame/MainMenu.cpp
ogsr_engine/xrGame/Weapon.cpp
ogsr_engine/xrGame/Weapon.h
ogsr_engine/xrGame/WeaponMagazined.cpp
ogsr_engine/xrGame/WeaponMagazinedWGrenade.cpp
ogsr_engine/xrGame/console_commands.cpp

- Disable second vid_restart when close main menu - vid_restart already begin applied in option manager UIOptionsManager already
- Added g_3d_scopes console command: allow to enable or disable lense scopes
- Added logic to hide texture scope and suppress scope_zoom_factor if g_3d_scopes is on
- Параметр scope_texture теперь не обязательный для оружия с прицелом - если не указан не будет текстурного прицела. Сделано что бы упростить создание коллиматоров или других прицелов где не нужна текстура
- Запретил переключения режима ПГ во время прицеливания - там багов больше чем пользы было.

Добавил отключение 3д прицелов через консоль + правки по оружейке

---

ogsr_engine/xrGame/Actor.cpp
ogsr_engine/xrGame/ActorCameras.cpp
ogsr_engine/xrGame/Weapon.cpp
ogsr_engine/xrGame/Weapon.h
ogsr_engine/xrGame/WeaponMagazined.cpp
ogsr_engine/xrGame/WeaponMagazined.h
ogsr_engine/xrGame/WeaponMagazinedWGrenade.cpp
ogsr_engine/xrGame/console_commands.cpp
ogsr_engine/xrGame/derived_client_classes.cpp
ogsr_engine/xr_3da/CameraManager.cpp
ogsr_engine/xr_3da/CameraManager.h
ogsr_engine/xr_3da/Environment_render.cpp
ogsr_engine/xr_3da/xr_ioc_cmd.cpp

1. Переделана логика работы **scope_dynamic_zoom** для прицелов с **scope_lense_fov_factor** - теперь динамический зум будет именно в линзе.
2. Добавил поддержку текстурных прицелов для оружие с **scope_status=2** когда снят прицел. Для включения нужно добавить **force_scope_texture=true** в секцию оружия.
3. Добавлены новые параметры к настройкам zoom offset/zoom rotate для оружия с scope_status=2 что бы отдельно настраивать прицеливание с прицелом и без него:
* Прицел установлен
scope_zoom_offset
scope_zoom_rotate_x
scope_zoom_rotate_y
* Прицел установлен вместе с ПГ
scope_grenade_normal_zoom_offset
scope_grenade_normal_zoom_rotate_x
scope_grenade_normal_zoom_rotate_y
* Прицел установлен в режиме ПГ
scope_grenade_zoom_offset
scope_grenade_zoom_rotate_x
scope_grenade_zoom_rotate_y
* Все …

Правки по оружию

---

ogsr_engine/COMMON_AI/PATH/patrol_path.cpp
ogsr_engine/COMMON_AI/PATH/patrol_path.h
ogsr_engine/COMMON_AI/PATH/patrol_path_storage.cpp
ogsr_engine/COMMON_AI/PATH/patrol_path_storage.h
ogsr_engine/COMMON_AI/PATH/patrol_point.cpp
ogsr_engine/COMMON_AI/PATH/patrol_point.h
ogsr_engine/xrCore/Xr_ini.cpp
ogsr_engine/xrCore/xr_ini.h
ogsr_engine/xrGame/GameTask.cpp
ogsr_engine/xrGame/WeaponMagazined.cpp
ogsr_engine/xrGame/ai_space.cpp
ogsr_engine/xrGame/ai_space.h
ogsr_engine/xrGame/alife_simulator_base.cpp
ogsr_engine/xrGame/alife_simulator_script.cpp
ogsr_engine/xrGame/alife_spawn_registry.cpp
ogsr_engine/xrGame/alife_spawn_registry.h
ogsr_engine/xrGame/alife_spawn_registry_inline.h
ogsr_engine/xrGame/alife_spawn_registry_spawn.cpp
ogsr_engine/xrGame/alife_surge_manager.cpp
ogsr_engine/xrGame/alife_surge_manager.h
ogsr_engine/xrGame/level_script.cpp
ogsr_engine/xrGame/ui/UITrackBar.cpp
ogsr_engine/xrGame/ui/UITrackBar.h
ogsr_engine/xrGame/ui/UIXmlInit.cpp

Формат файлов такой же, как выдает acdc при распаковке.
Для подключения, добавить system.ltx
```
[engine_custom_spawn]
waypoints_file = <name_of_file.ltx>
```
<name_of_file.ltx> - путь к файлу в $game_config$
При загрузке, пути из файла будут заменять пути из all.spawn с таким же именем.
Можно вообще убрать пути из своего all.spawn и все перенести в файлы, время загрузки всех путей порядка 0,2-0,3 сек из файлов.
Так же, немного выкинул мусор при создании НИ

Добавил поддержку чтение patrol_path из ltx файлов напрямую

---

Game/Resources_SoC_1.0006/gamedata/config/ui/ui_mm_opt.xml
Game/Resources_SoC_1.0006/gamedata/scripts/ui_mm_opt_gameplay.script
Game/Resources_SoC_1.0006/gamedata/scripts/ui_mm_opt_video_adv.script

Вкладки "Видео"(расширенные) и "Игра" теперь используют общий frame, вместо индивидуальных "frame_videoadv" и "frame_gameplay"
Не понятно зачем именно для этих вкладок сделаны свои frame'ы

Оптимизация

---

Game/Resources_SoC_1.0006/gamedata/config/ui/ui_mm_load_dlg.xml
Game/Resources_SoC_1.0006/gamedata/config/ui/ui_mm_opt.xml
Game/Resources_SoC_1.0006/gamedata/config/ui/ui_mm_save_dlg.xml

Исправление наложения(наложение размером в один логический пиксель) между краями кнопок: сохранить, загрузить, применить, отмена и удалить. 
Можно было нажать на две кнопки одновременно, что в оригинале иногда приводило к вылету, а здесь просто одна из нажатых кнопок "залипала".
P.S. Новые файлы были взяты из стим-версии

Исправление наложения кнопок
